/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background':                '#fcf9f2',
        'tertiary':                  '#390003',
        'on-surface-variant':        '#564240',
        'on-secondary-fixed':        '#281803',
        'tertiary-container':        '#600007',
        'surface-container':         '#f0eee7',
        'on-tertiary':               '#ffffff',
        'on-surface':                '#1c1c18',
        'surface-container-lowest':  '#ffffff',
        'on-tertiary-fixed':         '#410003',
        'surface-variant':           '#e5e2db',
        'primary-container':         '#5c0a0a',
        'inverse-primary':           '#ffb4ab',
        'surface-container-highest': '#e5e2db',
        'on-primary-fixed':          '#410002',
        'on-error-container':        '#93000a',
        'on-primary':                '#ffffff',
        'tertiary-fixed-dim':        '#ffb3ad',
        'on-secondary-container':    '#786044',
        'secondary-fixed-dim':       '#e0c29f',
        'surface-tint':              '#a13e36',
        'primary':                   '#390002',
        'on-primary-container':      '#e47166',
        'secondary':                 '#715a3e',
        'error-container':           '#ffdad6',
        'inverse-surface':           '#31312c',
        'on-error':                  '#ffffff',
        'surface-container-high':    '#ebe8e1',
        'surface-dim':               '#dcdad3',
        'on-primary-fixed-variant':  '#812721',
        'on-secondary':              '#ffffff',
        'on-tertiary-container':     '#f7615a',
        'error':                     '#ba1a1a',
        'inverse-on-surface':        '#f3f0ea',
        'on-background':             '#1c1c18',
        'secondary-container':       '#fdddb9',
        'primary-fixed-dim':         '#ffb4ab',
        'on-secondary-fixed-variant':'#584329',
        'on-tertiary-fixed-variant': '#8e1217',
        'outline-variant':           '#ddc0bd',
        'outline':                   '#89726f',
        'surface-container-low':     '#f6f3ec',
        'secondary-fixed':           '#fdddb9',
        'surface':                   '#fcf9f2',
        'primary-fixed':             '#ffdad6',
        'tertiary-fixed':            '#ffdad6',
        'surface-bright':            '#fcf9f2',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
}
