// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	SessionID string `json:"sessionId"`
	User      *User  `json:"user"`
}

type Character struct {
	ID                    string          `json:"id"`
	Name                  string          `json:"name"`
	Species               string          `json:"species"`
	SubSpecies            *string         `json:"subSpecies,omitempty"`
	Class                 string          `json:"class"`
	Level                 int             `json:"level"`
	Ruleset               string          `json:"ruleset"`
	BaseStats             *Stats          `json:"baseStats"`
	FinalStats            *Stats          `json:"finalStats"`
	Modifiers             *Stats          `json:"modifiers"`
	Derived               *DerivedStats   `json:"derived"`
	Background            *NarrativeBlock `json:"background"`
	Motivation            *NarrativeBlock `json:"motivation"`
	Secret                *NarrativeBlock `json:"secret"`
	Locks                 *CharacterLocks `json:"locks"`
	Seed                  *int            `json:"seed,omitempty"`
	BackgroundType        string          `json:"backgroundType"`
	AsiDistribution       string          `json:"asiDistribution"`
	OriginFeat            string          `json:"originFeat"`
	BackgroundDescription string          `json:"backgroundDescription"`
	CreatedAt             string          `json:"createdAt"`
	UpdatedAt             string          `json:"updatedAt"`
}

type CharacterLocks struct {
	Name       bool `json:"name"`
	Stats      bool `json:"stats"`
	Background bool `json:"background"`
	Motivation bool `json:"motivation"`
	Secret     bool `json:"secret"`
}

type CharacterLocksInput struct {
	Name       bool `json:"name"`
	Stats      bool `json:"stats"`
	Background bool `json:"background"`
	Motivation bool `json:"motivation"`
	Secret     bool `json:"secret"`
}

type CurrentCharacterInput struct {
	Name       string               `json:"name"`
	Class      string               `json:"class"`
	Species    string               `json:"species"`
	SubSpecies *string              `json:"subSpecies,omitempty"`
	Gender     *string              `json:"gender,omitempty"`
	Seed       *int                 `json:"seed,omitempty"`
	FinalStats *StatsInput          `json:"finalStats"`
	Derived    *DerivedStatsInput   `json:"derived"`
	Background *NarrativeBlockInput `json:"background"`
	Motivation *NarrativeBlockInput `json:"motivation"`
	Secret     *NarrativeBlockInput `json:"secret"`
}

type DerivedStats struct {
	Hp int `json:"hp"`
	Ac int `json:"ac"`
}

type DerivedStatsInput struct {
	Hp int `json:"hp"`
	Ac int `json:"ac"`
}

type EditCharacterInput struct {
	Name       *string `json:"name,omitempty"`
	Background *string `json:"background,omitempty"`
	Motivation *string `json:"motivation,omitempty"`
	Secret     *string `json:"secret,omitempty"`
}

type GenerateCharacterInput struct {
	Name       *string `json:"name,omitempty"`
	Class      *string `json:"class,omitempty"`
	Species    *string `json:"species,omitempty"`
	SubSpecies *string `json:"subSpecies,omitempty"`
	Gender     *string `json:"gender,omitempty"`
	Seed       *int    `json:"seed,omitempty"`
}

type Mutation struct {
}

type NarrativeBlock struct {
	Category string   `json:"category"`
	Content  string   `json:"content"`
	Tags     []string `json:"tags"`
}

type NarrativeBlockInput struct {
	Category string   `json:"category"`
	Content  string   `json:"content"`
	Tags     []string `json:"tags"`
}

type Query struct {
}

type Stats struct {
	Str int `json:"STR"`
	Dex int `json:"DEX"`
	Con int `json:"CON"`
	Int int `json:"INT"`
	Wis int `json:"WIS"`
	Cha int `json:"CHA"`
}

type StatsInput struct {
	Str int `json:"STR"`
	Dex int `json:"DEX"`
	Con int `json:"CON"`
	Int int `json:"INT"`
	Wis int `json:"WIS"`
	Cha int `json:"CHA"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
