package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"forge-rpg/graph/generated"
	"forge-rpg/graph/model"
	"forge-rpg/internal/domain"
	graphqlmw "forge-rpg/internal/infrastructure/graphql"
	"forge-rpg/internal/usecase/character"
	"forge-rpg/internal/usecase/statblock"
	"time"
)

// RequestMagicLink is the resolver for the requestMagicLink field.
func (r *mutationResolver) RequestMagicLink(ctx context.Context, email string) (bool, error) {
	err := r.auth.RequestMagicLink(ctx, email)
	if err != nil {
		return false, err
	}
	return true, nil
}

// VerifyMagicLink is the resolver for the verifyMagicLink field.
func (r *mutationResolver) VerifyMagicLink(ctx context.Context, token string) (*model.AuthPayload, error) {
	session, user, err := r.auth.VerifyMagicLink(ctx, token)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		SessionID: session.ID,
		User: &model.User{
			ID:    user.ID,
			Email: user.Email,
		},
	}, nil
}

// Logout is the resolver for the logout field.
// Reads the session ID from context (set by AuthMiddleware) and delegates deletion to the auth service.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	sessionID, ok := ctx.Value(graphqlmw.SessionContextKey).(string)
	if !ok || sessionID == "" {
		return false, fmt.Errorf("not authenticated")
	}
	err := r.auth.Logout(ctx, sessionID)
	return err == nil, err
}

// GenerateCharacter is the resolver for the generateCharacter field.
// Does NOT require authentication — generation is stateless and available to anyone.
func (r *mutationResolver) GenerateCharacter(ctx context.Context, input *model.GenerateCharacterInput) (*model.Character, error) {
	ci := inputToCreateInput(input, nil)
	c, err := r.creator.Create(ctx, ci)
	if err != nil {
		return nil, fmt.Errorf("generateCharacter: %w", err)
	}
	return toModelCharacter(c), nil
}

// RegenerateCharacter is the resolver for the regenerateCharacter field.
// Requires auth — it operates on a persisted character and updates it in place.
func (r *mutationResolver) RegenerateCharacter(ctx context.Context, id string, locks model.CharacterLocksInput, seed *int) (*model.Character, error) {
	user, err := userFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	existing, err := r.manager.Get(ctx, user.ID, id)
	if err != nil {
		return nil, fmt.Errorf("regenerateCharacter: %w", err)
	}

	domainLocks := domain.CharacterLocks{
		Name:       locks.Name,
		Stats:      locks.Stats,
		Background: locks.Background,
		Motivation: locks.Motivation,
		Secret:     locks.Secret,
	}

	var seedPtr *int64
	if seed != nil {
		s := int64(*seed)
		seedPtr = &s
	}

	updated, err := r.creator.Regenerate(ctx, character.RegenerateInput{
		Character: existing,
		Locks:     domainLocks,
		Seed:      seedPtr,
	})
	if err != nil {
		return nil, fmt.Errorf("regenerateCharacter: %w", err)
	}

	if err := r.manager.Save(ctx, user.ID, updated); err != nil {
		return nil, fmt.Errorf("regenerateCharacter: save: %w", err)
	}

	return toModelCharacter(updated), nil
}

// RegenerateDraft is the resolver for the regenerateDraft field.
// Stateless — rebuilds unlocked fields from the client-supplied current state, no DB access.
func (r *mutationResolver) RegenerateDraft(ctx context.Context, current model.CurrentCharacterInput, locks model.CharacterLocksInput, seed *int) (*model.Character, error) {
	if current.FinalStats == nil || current.Derived == nil {
		return nil, fmt.Errorf("regenerateDraft: finalStats and derived are required")
	}
	if current.Background == nil || current.Motivation == nil || current.Secret == nil {
		return nil, fmt.Errorf("regenerateDraft: background, motivation and secret are required")
	}

	// Convert finalStats input → domain.Stats
	finalStats := domain.Stats{
		STR: current.FinalStats.Str,
		DEX: current.FinalStats.Dex,
		CON: current.FinalStats.Con,
		INT: current.FinalStats.Int,
		WIS: current.FinalStats.Wis,
		CHA: current.FinalStats.Cha,
	}

	// Convert narrative blocks
	background := domain.NarrativeBlock{
		Category: domain.NarrativeCategory(current.Background.Category),
		Content:  current.Background.Content,
		Tags:     current.Background.Tags,
	}
	motivation := domain.NarrativeBlock{
		Category: domain.NarrativeCategory(current.Motivation.Category),
		Content:  current.Motivation.Content,
		Tags:     current.Motivation.Tags,
	}
	secret := domain.NarrativeBlock{
		Category: domain.NarrativeCategory(current.Secret.Category),
		Content:  current.Secret.Content,
		Tags:     current.Secret.Tags,
	}

	// Optional subSpecies
	var subSpecies *domain.SubSpecies
	if current.SubSpecies != nil {
		ss := domain.SubSpecies(*current.SubSpecies)
		subSpecies = &ss
	}

	// Pre-compute modifiers from finalStats so locked-stats path returns correct modifiers.
	modifiers := domain.Modifiers{
		STR: statblock.CalculateModifier(finalStats.STR),
		DEX: statblock.CalculateModifier(finalStats.DEX),
		CON: statblock.CalculateModifier(finalStats.CON),
		INT: statblock.CalculateModifier(finalStats.INT),
		WIS: statblock.CalculateModifier(finalStats.WIS),
		CHA: statblock.CalculateModifier(finalStats.CHA),
	}

	derived := domain.DerivedStats{
		HP: current.Derived.Hp,
		AC: current.Derived.Ac,
	}

	now := time.Now()
	draft := &domain.Character{
		ID:                 "draft",
		UserID:             "",
		Name:               current.Name,
		Species:            domain.Species(current.Species),
		Class:              domain.Class(current.Class),
		SubSpecies:         subSpecies,
		Level:              1,
		Ruleset:            domain.Ruleset5e,
		AbilityBonusSource: domain.AbilityBonusFromBackground,
		BaseStats:          finalStats,
		FinalStats:         finalStats,
		Modifiers:          modifiers,
		Derived:            derived,
		Background:         background,
		Motivation:         motivation,
		Secret:             secret,
		Locks:              domain.CharacterLocks{},
		CreatedAt:          now,
		UpdatedAt:          now,
	}

	domainLocks := domain.CharacterLocks{
		Name:       locks.Name,
		Stats:      locks.Stats,
		Background: locks.Background,
		Motivation: locks.Motivation,
		Secret:     locks.Secret,
	}

	var seedPtr *int64
	if seed != nil {
		s := int64(*seed)
		seedPtr = &s
	}

	result, err := r.creator.Regenerate(ctx, character.RegenerateInput{
		Character: draft,
		Locks:     domainLocks,
		Seed:      seedPtr,
	})
	if err != nil {
		return nil, fmt.Errorf("regenerateDraft: %w", err)
	}

	return toModelCharacter(result), nil
}

// SaveCharacter is the resolver for the saveCharacter field.
// Regenerates a character deterministically from seed+input, then persists it.
// Requires auth.
func (r *mutationResolver) SaveCharacter(ctx context.Context, input model.GenerateCharacterInput, seed int) (*model.Character, error) {
	user, err := userFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	s := int64(seed)
	ci := inputToCreateInput(&input, &s)

	c, err := r.creator.Create(ctx, ci)
	if err != nil {
		return nil, fmt.Errorf("saveCharacter: generate: %w", err)
	}

	if err := r.manager.Save(ctx, user.ID, c); err != nil {
		return nil, fmt.Errorf("saveCharacter: persist: %w", err)
	}

	return toModelCharacter(c), nil
}

// EditCharacter is the resolver for the editCharacter field.
// Requires auth.
func (r *mutationResolver) EditCharacter(ctx context.Context, id string, input model.EditCharacterInput) (*model.Character, error) {
	user, err := userFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	editIn := character.EditInput{
		Name:       input.Name,
		Background: input.Background,
		Motivation: input.Motivation,
		Secret:     input.Secret,
	}

	c, err := r.manager.Edit(ctx, user.ID, id, editIn)
	if err != nil {
		return nil, fmt.Errorf("editCharacter: %w", err)
	}

	return toModelCharacter(c), nil
}

// DeleteCharacter is the resolver for the deleteCharacter field.
// Requires auth.
func (r *mutationResolver) DeleteCharacter(ctx context.Context, id string) (bool, error) {
	user, err := userFromCtx(ctx)
	if err != nil {
		return false, err
	}

	if err := r.manager.Delete(ctx, user.ID, id); err != nil {
		return false, fmt.Errorf("deleteCharacter: %w", err)
	}

	return true, nil
}

// Me is the resolver for the me field.
// Returns nil (not an error) when unauthenticated.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, ok := ctx.Value(graphqlmw.UserContextKey).(*domain.User)
	if !ok || user == nil {
		return nil, nil
	}
	return &model.User{
		ID:    user.ID,
		Email: user.Email,
	}, nil
}

// Characters is the resolver for the characters field.
// Requires auth.
func (r *queryResolver) Characters(ctx context.Context) ([]*model.Character, error) {
	user, err := userFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	chars, err := r.manager.List(ctx, user.ID)
	if err != nil {
		return nil, fmt.Errorf("characters: %w", err)
	}

	return toModelCharacters(chars), nil
}

// Character is the resolver for the character field.
// Requires auth.
func (r *queryResolver) Character(ctx context.Context, id string) (*model.Character, error) {
	user, err := userFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	c, err := r.manager.Get(ctx, user.ID, id)
	if err != nil {
		return nil, fmt.Errorf("character: %w", err)
	}

	return toModelCharacter(c), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
